Option decorator
vulcan-api/spito pull request #125
Opened 2024-02-24 21:53 UTC by cooligus

2024-02-26 08:09 UTC, sewe2000 commented on pkg/shared/option/compare.go
> +		value := userOption[splitPos+1:]
What about?
``` go
name, value, foundOption := strings.Cut(userOption, "=")
```

2024-02-26 14:50 UTC, cooligus commented on internal/lua_tests/options_test.lua
> +        gender:{male;female}=male,
`gender?:{male;female}=male` is what you want

2024-02-29 17:03 UTC, BaderBC requested changes

2024-02-29 17:33 UTC, cooligus commented on pkg/shared/option/option.go
> +	}
Can you give me an example (sample code)?

2024-02-29 17:33 UTC, cooligus commented on cmd/guiApi/info.go
There is eg. displaying arrays

2024-02-29 17:36 UTC, cooligus commented on pkg/shared/option/option.go
> +func GetType(rawValue any) Type {
Can you explain?

2024-03-01 08:10 UTC, BaderBC commented on pkg/shared/option/option.go
> +func GetType(rawValue any) Type {
https://go.dev/tour/methods/16

2024-03-02 18:06 UTC, cooligus commented on internal/lua_tests/options_test.lua
> +        gender:{male;female}=male,
Yes but it's empty string

2024-03-02 18:12 UTC, cooligus commented on internal/checker/interpreter.go
> +}
How to convert `[]string` to `lua.LValue`?

2024-03-19 12:54 UTC, BaderBC commented
Please remove dependa bot from gh actions

2024-03-20 15:18 UTC, BaderBC approved these changes
Currently I don't really care about this project, so I approved it hoping this pr won't break anything.

2024-03-21 10:02 UTC, merged